services:
  postgres:
    image: postgres:14
    container_name: hora-vital-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hora-vital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
